### PR TITLE
Merge #2, #17, #18, #19 and drop Python 2 support

### PR DESCRIPTION
**Pull request by iyzsong**
Hello, I'd like package speedometer for guix (https://issues.guix.gnu.org/52094), but first make it to use python3 instead...

Tested on Guix System (with Linux kernel) and OpenBSD, also I could help maintain this project, I'm familiar with python (but not urwid yet).

Thank you!

### CODE REVIEW

**Comment by jxu** [comment]
@wardi ?

@iyzsong send him an email, sometimes original authors don't see PRs

**Comment by iyzsong** [comment]
@wardi Looking forward to it, thank you!

**Comment by jxu** [comment]
You're welcome

**Comment by wardi** [comment]
@iyzsong I've given you collaborator access to this repo, please feel free to push changes to master. Give me your pypi account details and I can give you permission to update the project there too.

**Comment by iyzsong** [comment]
@wardi thanks, my pypi username is `iyzsong`, and its email is `iyzsong@envs.net`.

**Comment by BenjaminHCCarr** [comment]
Awesome @iyzsong and @wardi

mind tagging a `2.9` release?

**Comment by wardi** [comment]
@iyzsong you should have a pypi invite now. The project page is on my personal site, so for now send me a PR when you need changes: https://github.com/wardi/wardi.github.io/blob/master/_pages/speedometer.md

**Comment by iyzsong** [comment]
@BenjaminHCCarr `release-2.9` tagged now, thank you.

@wardi Sorry I missed the invite link, it's expired now, could you send it again, thank you!

**Comment by wardi** [comment]
@iyzsong sent again

**Comment by iyzsong** [comment]
@wardi get it, thanks!

**Pull request merged**
